services:
  labrat:
    build: .
    container_name: labrat
    volumes:
      - .:/workspace
    environment:
      - OPENAI_API_KEY
      - HUGGINGFACEHUB_API_TOKEN
      - GITHUB_TOKEN
      - OPENWEBUI_URL
      - OLLAMA_URL
      - POSTGRES_URL
      - CHROMADB_URL
      - QDRANT_URL
    stdin_open: true
    tty: true