version: '3.8'
services:
  labrat:
    build: .
    container_name: labrat
    volumes:
      - .:/workspace
    environment:
      - OPENAI_API_KEY
      - HUGGINGFACEHUB_API_TOKEN
      - GITHUB_TOKEN
      - OPENWEBUI_URL
      - OLLAMA_URL
      - POSTGRES_URL
      - CHROMADB_URL
      - QDRANT_URL
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - chromadb
      - qdrant

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: labrat
      POSTGRES_PASSWORD: labrat
      POSTGRES_DB: labrat
    ports:
      - "5432:5432"

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"